# Generated by Django 3.1.7 on 2021-05-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buses', models.CharField(max_length=90, verbose_name='Nombre bus:')),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripción: ')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
            },
        ),
    ]
