# Generated by Django 3.2.3 on 2021-05-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
