# Generated by Django 3.2.3 on 2021-05-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_bus_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='descripcion',
            field=models.CharField(max_length=1000, verbose_name='Descripción: '),
        ),
    ]
